[build]
builder = "dockerfile"

[deploy]
startCommand = "python backend/run.py"
healthcheckPath = "/api/ping"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "langgraph-agent"

[services.variables]
PORT = "8000"
BACKEND_PORT = "8000"
FRONTEND_PORT = "9002"